# Generated by Django 3.2.13 on 2022-06-14 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0006_auto_20220614_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(blank=True, null=True, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 16, 41, 38, 44801), verbose_name='添加时间'),
        ),
    ]
