# Generated by Django 3.2.13 on 2022-06-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('path', models.CharField(max_length=100)),
            ],
        ),
    ]
