# Generated by Django 3.2.13 on 2022-06-13 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0002_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgs',
            name='author',
            field=models.CharField(default='amy', max_length=100, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='content',
            field=models.CharField(default='', max_length=1000, verbose_name='内容'),
        ),
        migrations.AddField(
            model_name='imgs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 10, 8, 16, 839321), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='name',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='imgs',
            name='path',
            field=models.ImageField(upload_to='img_url/', verbose_name='图片地址'),
        ),
    ]
