# Generated by Django 3.2.13 on 2022-06-13 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0004_auto_20220613_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=200, verbose_name='标题')),
            ],
        ),
        migrations.RenameField(
            model_name='news',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 11, 19, 5, 267739), verbose_name='添加时间'),
        ),
    ]
