# Generated by Django 3.2.13 on 2022-06-14 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0005_auto_20220613_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='comments',
            field=models.CharField(default='', max_length=1000, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 16, 38, 35, 410456), verbose_name='添加时间'),
        ),
    ]
