# Generated by Django 3.2.13 on 2022-06-14 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0008_auto_20220614_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(blank=True, default=0, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 16, 46, 54, 838008), verbose_name='添加时间'),
        ),
    ]
