# Generated by Django 3.2.13 on 2022-06-14 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gctApp', '0010_auto_20220614_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.IntegerField(blank=True, null=True, verbose_name='喜欢'),
        ),
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 17, 16, 32, 20700), verbose_name='添加时间'),
        ),
    ]
